### ISSUE TITLE
Documentation for the API section of the app

### ISSUE THREAD

**Issue by yasharth291** [Incentive-Coders/Shared-Backpack-docs#5]
Documentation for the API section of the app should be written in the markdown

**Comment by sejalrai23** [comment]
i want to work on this .please assign it to me.

**Comment by yasharth291** [comment]
ok gtgo

**Comment by gurvinder-yadav** [comment]
please assign me this issue.

**Comment by yasharth291** [comment]
sure @gurvinder-yadav
